// <auto-generated />
using System;
using Leitor.Erp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

namespace Leitor.Erp.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20260804000003_AddQuoteProposalPriceListId")]
    partial class AddQuoteProposalPriceListId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.7");
#pragma warning restore 612, 618
        }
    }
}
